### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by konkiiii** [konkiiii/protospace-38526#5]

**Comment by ghost** [comment]
@konkiiii さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

**プロトタイプ一覧表示機能**
- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するようにしましょう**
現在、ログアウトの状態で１つ目の投稿の画像およびプロトタイプ名をクリックすると、エラー画面に遷移してしまいます。ログアウト状態でも、全てのプロトタイプの詳細ページへ遷移できるようにしましょう。


https://user-images.githubusercontent.com/116065064/212503102-38f8bbd3-8fb4-4d62-8a18-c5da4b3a9214.mov



**プロトタイプ削除機能**
- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう**
現在、削除ボタンを押すとエラー画面に遷移し、削除ができない状態です。
削除の処理ができるようにしましょう。


**ユーザー詳細機能**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
現在、ログアウトの状態で各ページのユーザー名をクリックすると、ログイン画面に遷移してしまいます。ログアウトの状態でも各ページのユーザー名から、該当するユーザーの詳細ページに遷移するようにしましょう。




修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
挙動確認を行い、修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
　https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by konkiiii** [comment]
@maru2628
確認ありがとうございます。

**Comment by shodai-ito** [comment]
@konkiiii さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
